### ISSUE TITLE
answer機能

### ISSUE THREAD

**Issue by shibatadaiki** [shibatadaiki/dive23_16#6]
・questionに紐付くanswer

DIVE15のコメント機能などを参考にしつつ、 質問に対してアンサーを投稿できるようにする。

`必須要件`

```
 ログインしていなければ回答できないようにする
 アンサーはひもづく質問の下にパーシャルで表示する（DIVE15のコメント機能と同じ）
 アンサーに回答者の名前を紐付けて表示できるようにする
 アンサーを削除できるようにする
 アンサーを編集できるようにする
 アンサーを編集・削除できるのは投稿者だけにする
 アンサー数の表示（その質問に紐づいている回答の数を、質問詳細画面のわかりやすい位置に配置する）
 アンサー投稿時間の表示
 自分のマイページで自分のしたアンサーの一覧を見れるようにする
 アンサーは遅く回答されたものが一番上に来るように表示する
 BootstrapとCSSで一定のデザインを整える
 アンサーした投稿者の名前を表示
 seedデータを作成しておく
 適切なバリデーションを設定すること
 アンサー投稿者のプロフィール画像をアンサーに表示する
```

バリデーションのテキスト
https://diver.diveintocode.jp/textbooks/640
https://diver.diveintocode.jp/textbooks/641

`追加要件（余力があれば）`

```
 アンサーの編集・削除を動的にできるようにする
```

**Comment by mem0112mem** [comment]
- [ ] issue#6-1 ログインしていなければ回答できないようにする
- [ ] issue#6-2 アンサーはひもづく質問の下にパーシャルで表示する（DIVE15のコメント機能と同じ）
- [ ] issue#6-3 アンサーに回答者の名前を紐付けて表示できるようにする
- [ ] issue#6-4 アンサーを削除できるようにする
- [ ] issue#6-5 アンサーを編集できるようにする
- [ ] issue#6-6 アンサーを編集・削除できるのは投稿者だけにする
- [ ] issue#6-7 アンサー数の表示（その質問に紐づいている回答の数を、質問詳細画面のわかりやすい位置に配置する）
- [ ] issue#6-8 アンサー投稿時間の表示
- [ ] issue#6-9 自分のマイページで自分のしたアンサーの一覧を見れるようにする
- [ ] issue#6-10 アンサーは遅く回答されたものが一番上に来るように表示する
- [ ] issue#6-11 BootstrapとCSSで一定のデザインを整える
- [ ] issue#6-12 アンサーした投稿者の名前を表示
- [ ] issue#6-13 seedデータを作成しておく
- [ ] issue#6-14 適切なバリデーションを設定すること
- [ ] issue#6-15 アンサー投稿者のプロフィール画像をアンサーに表示する
